apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sift.fullname" . }}-config
  labels:
    {{- include "sift.labels" . | nindent 4 }}
data:
  sift.yaml: |
    subfinder:
      timeout: {{ .Values.config.subfinderTimeout | quote }}
    port_scanner:
      ports: {{ .Values.config.portScannerPorts | quote }}
    scanning:
      packets_per_second: {{ .Values.config.scanningPacketsPerSecond }}
