apiVersion: v1
kind: Service
metadata:
  name: {{ include "sift.fullname" . }}-nats
  labels:
    {{- include "sift.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.nats.port }}
      name: client
      targetPort: 4222
  selector:
    app: {{ include "sift.fullname" . }}-nats
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sift.fullname" . }}-nats-headless
  labels:
    {{- include "sift.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.nats.port }}
      name: client
      targetPort: 4222
    - port: {{ .Values.nats.clusterPort }}
      name: cluster
      targetPort: 6222
  selector:
    app: {{ include "sift.fullname" . }}-nats
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sift.fullname" . }}-nats
  labels:
    {{- include "sift.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "sift.fullname" . }}-nats-headless
  replicas: {{ .Values.nats.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "sift.fullname" . }}-nats
  template:
    metadata:
      labels:
        app: {{ include "sift.fullname" . }}-nats
    spec:
      containers:
        - name: nats
          image: {{ .Values.nats.image }}
          args:
            - "-js"
            - "-sd"
            - "/data"
            {{- if gt (int .Values.nats.replicaCount) 1 }}
            - "--cluster"
            - "nats://0.0.0.0:6222"
            - "--routes"
            - "nats-0.{{ include "sift.fullname" . }}-nats-headless:6222,nats-1.{{ include "sift.fullname" . }}-nats-headless:6222,nats-2.{{ include "sift.fullname" . }}-nats-headless:6222"
            {{- end }}
          ports:
            - containerPort: 4222
              name: client
            - containerPort: 6222
              name: cluster
          volumeMounts:
            - name: nats-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: nats-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.global.storageClass }}
        storageClassName: {{ .Values.global.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: 2Gi
