apiVersion: v1
kind: Service
metadata:
  name: {{ include "sift.fullname" . }}-postgres
  labels:
    {{- include "sift.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: 5432
  selector:
    app: {{ include "sift.fullname" . }}-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sift.fullname" . }}-postgres
  labels:
    {{- include "sift.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "sift.fullname" . }}-postgres
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "sift.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "sift.fullname" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-db
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-db
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.global.storageClass }}
        storageClassName: {{ .Values.global.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgres.storage.size }}
