apiVersion: v1
kind: Service
metadata:
  name: {{ include "sift.fullname" . }}-redis
  labels:
    {{- include "sift.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: 6379
  selector:
    app: {{ include "sift.fullname" . }}-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sift.fullname" . }}-redis
  labels:
    {{- include "sift.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sift.fullname" . }}-redis
  template:
    metadata:
      labels:
        app: {{ include "sift.fullname" . }}-redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: 6379
              name: redis
